// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yzwmoyvprpqcnsjfasns.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl6d21veXZwcnBxY25zamZhc25zIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYzNTM0NDgsImV4cCI6MjA3MTkyOTQ0OH0.cqejVQJho5WhqmZoRWbPoxw43VqDwkG-08jZWwH43VU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});